### ISSUE TITLE
trouble reading PMU data

### ISSUE THREAD

**Issue by musawir8012** [iicsys/pypmu#12]
i am trying to acquire PMU data using this library but i am getting following error:
'Received unknown message from PMU'
![Capture](https://user-images.githubusercontent.com/52913768/61206576-53452f80-a70c-11e9-848c-6f0674700bcc.PNG)
can anyone tell me how to solve this issue

**Comment by sstevan** [comment]
Hey @musawir8012 ,

Would you mind sending us the `.pcap` file (record it with Wireshark), so we can check what is happening?

**Comment by ice66666** [comment]
I have the same question, could you tell me how to solve it ?
![image](https://user-images.githubusercontent.com/47851010/63105667-2f7a4100-bf79-11e9-8e3c-cea2ff4338dc.png)
![image](https://user-images.githubusercontent.com/47851010/63106005-cf37cf00-bf79-11e9-8b80-a22c4ea8a650.png)

**Comment by sstevan** [comment]
Hello @ice66666,

Please send me the .pcap file you captured or simply copy the content of the IEEE C37.118 message here.

**Comment by ice66666** [comment]
The .pcap file was attached. Thank you in advance.
________________________________

**Comment by sstevan** [comment]
@ice66666 I can see only two screenshots. I will need the actual recorded `.pcap` file. I need to copy the content of the C37.118 message (not to rewrite it from screenshot).
