### ISSUE TITLE
IEEE standard

### ISSUE THREAD

**Issue by MMAThijssen** [iicsys/pypmu#13]
Hi, 

The package was based on the standard from 2011. Currently, the synchrophasor standard IEEE 60255-118-1-2018 is in place. Has this been updated? What would the implications be of use as is?

Thank you!

**Comment by sstevan** [comment]
Hey @MMAThijssen 

Sorry about the delay. Each frame carries info about the standard version. Changes made in 2018 are not implemented (also Configuration Frame version 3 is not implemented). 

However, depending on your use case, this package will work just fine if you are able to set the appropriate version on devices/simulators.

**Comment by MMAThijssen** [comment]
Thank you for your reply! I will have to look if it is applicable for my use case. Anyways, it is clear to me what standard version the package is based on.
