### ISSUE TITLE
Propper short integer checks

### ISSUE THREAD

**Issue by SophieAltenburg** [iicsys/pypmu#26]
The range for short integers is -32768 to 32767 instead of -32767 to 32767, isn't it? The frame.py file checks for the second (wrong?) range.

**Comment by sstevan** [comment]
Hey @SophieAltenburg,

We have implemented this by following the C32.118.2 standard. Also please check out [this](https://en.wikipedia.org/wiki/C_data_types#:~:text=short%20int,least%2016%20bits%20in%20size.) article.
![Screenshot from 2020-07-31 20-43-28](https://user-images.githubusercontent.com/7474340/89066975-b1bc6a80-d36e-11ea-9b42-64f399d159a1.png)
