### ISSUE TITLE
PyPMU how to connect to openpdc

### ISSUE THREAD

**Issue by haoyu112** [iicsys/pypmu#31]
Hello,
I try to use the package Synchrophsor package in Python to connect with the OpenPDC. However, I meet some problems that the progress appears Received unknown messages. Could you tell me how to develop the progress to solve this Problem.
![微信图片_20210909205340](https://user-images.githubusercontent.com/90436214/132797169-d5520a1e-d8ea-4d53-966d-113f0d93edf7.png)

**Comment by sstevan** [comment]
Hey @haoyu112,

You can delete line number 7 since `get_header()` does not do anything specific (returns header message).
However, you will need to get a configuration frame (line 8) somehow because PDC needs it to unpack values.

**Comment by haoyu112** [comment]
![image](https://user-images.githubusercontent.com/90436214/132997480-1977942c-53c5-45b5-8a24-1841f6c6108e.png)
![image](https://user-images.githubusercontent.com/90436214/132998317-d91ab5d7-65f0-4a44-9ac4-00c6448bb48c.png)

hello ssteven,
I delete the line number 7, but when I run Pdc.get. I get nothing. Could you help me to solve the problem?

**Comment by haoyu112** [comment]
> Hey @haoyu112,
> 
> You can delete line number 7 since `get_header()` does not do anything specific (returns header message).
> However, you will need to get a configuration frame (line 8) somehow because PDC needs it to unpack values.

https://user-images.githubusercontent.com/90436214/132998317-d91ab5d7-65f0-4a44-9ac4-00c6448bb48c.png
hello ssteven,
I delete the line number 7, but when I run Pdc.get. I get nothing. Could you help me to solve the problem?
https://user-images.githubusercontent.com/90436214/132997480-1977942c-53c5-45b5-8a24-1841f6c6108e.png
However, I find these are some information in get_config
